### ISSUE TITLE
unexpanded command substitution?

### ISSUE THREAD

**Issue by kingslef** [openshift/leader-elector#20]
Looks like the entrypoint doesn't substitute the command [here](https://github.com/openshift/leader-elector/blob/master/Dockerfile#L14):
```
ENTRYPOINT [ "leader-elector", "--id=$(hostname)" ]
```

As explained in https://docs.docker.com/engine/reference/builder/#exec-form-entrypoint-example, the normal shell processing doesn't happen, leaving literal `$(hostname)` to the leader-elector arguments.

One way to fix it could be calling a script like the [`run.sh`](https://github.com/openshift/leader-elector/blob/master/election/run.sh).

**Comment by sivagotety** [comment]
> Looks like the entrypoint doesn't substitute the command [here](https://github.com/openshift/leader-elector/blob/master/Dockerfile#L14):
> 
> ```
> ENTRYPOINT [ "leader-elector", "--id=$(hostname)" ]
> ```
> 
> As explained in https://docs.docker.com/engine/reference/builder/#exec-form-entrypoint-example, the normal shell processing doesn't happen, leaving literal `$(hostname)` to the leader-elector arguments.
> 
> One way to fix it could be calling a script like the [`run.sh`](https://github.com/openshift/leader-elector/blob/master/election/run.sh).

Amazing solution thank-you, you are a legend
